Add documentation for how to generate MAPI TS types and client functions
giantswarm/happa pull request #3844
Opened 2022-10-28 14:46 UTC by kuosandys

### What does this PR do?

This PR adds documentation for how to generate TS types and client functions to FE docs, as implemented in https://github.com/giantswarm/happa/pull/3822 and https://github.com/giantswarm/happa/pull/3843.

### Any background context you can provide?

As a last step to https://github.com/giantswarm/roadmap/issues/1528.

### Do the docs need to be updated?

Yes we're doing it with this PR 🙃

2022-10-31 07:29 UTC, mogottsch requested changes
Clear documentation :+1: 
I think `scripts/generate/mapi-resources.yaml` should be `scripts/generateTypes/mapi-resources.yaml`, right?

2022-10-31 07:29 UTC, mogottsch commented on src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
> +This generates TS types and MAPI client functions for resources declared in [`scripts/generate/mapi-resources.yaml`](`https://github.com/giantswarm/happa/blob/main/scripts/generate/mapi-resources.yam
It's `scripts/generateTypes/mapi-resources.yaml`, right?

2022-10-31 07:29 UTC, mogottsch commented on src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
> +Resources for which we wish to generate TS types and client functions can be declared in [`scripts/generate/mapi-resources.yaml`](`https://github.com/giantswarm/happa/blob/main/scripts/generate/mapi-
same here

2022-10-31 07:29 UTC, mogottsch commented on src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
> +For most cases it should not be necessary to overwrite the types defined by the schema defined in the resource's CRD. However, to allow the generated TS types to work better with happa's codebase, cu
same here

2022-11-02 08:42 UTC, kuosandys commented
> I think `scripts/generate/mapi-resources.yaml` should be `scripts/generateTypes/mapi-resources.yaml`, right?

The folder was renamed with https://github.com/giantswarm/happa/pull/3843 since the code in the folder wasn't just about generating types anymore 😅 I should have clarified in the PR description that this docs change depends on the changes in that pull request - thanks for pointing it out! I've updated the branch and the description above 🙂

2022-11-02 09:45 UTC, gusevda commented on src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
> +    crdURL: https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-gcp/main/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
should we add `verbs` here?

2022-11-02 09:50 UTC, kuosandys commented on src/stories/GeneratingMapiTypesClientFunctions.stories.mdx
> +    crdURL: https://raw.githubusercontent.com/kubernetes-sigs/cluster-api-provider-gcp/main/config/crd/bases/infrastructure.cluster.x-k8s.io_gcpclusters.yaml
Yes, we should 😄

2022-11-02 13:07 UTC, gusevda approved these changes
Looks good!

2022-11-03 07:07 UTC, mogottsch approved these changes

2022-11-03 07:52 UTC, merged